### ISSUE TITLE
Text-based content search

### ISSUE THREAD

**Issue by Feld0** [Poniverse/Pony.fm#1]
A text-based search will users to quickly find tracks, albums, artists, and playlists - all of Pony.fm's content types - when they already know what they're looking for. This will complement Pony.fm's current taxonomies, which are more appropriate for discovering new music than finding something specific.

The feature should be implemented so as to return results "live" as the user types their query. Elasticsearch should probably back it.

**Comment by kz** [comment]
Just a word of warning that ElasticSearch's default setting is that it will listen on all addresses, opening up the ES server to the public. It will need to be changed to localhost as soon as it's installed.

**Comment by Feld0** [comment]
This is implemented, deployed, and working! :smile:
