### ISSUE TITLE
Migrate from Mcrypt to newer openssl based one

### ISSUE THREAD

**Issue by Lavoaster** [Poniverse/Pony.fm#108]
As part of the Laravel 5.3 upgrade, I opted to reinstate the Mcrypt provider so that we could get a working application in production.  This needs to be updated and upgraded. 

As detailed on [this](https://laravel.com/docs/5.3/upgrade#upgrade-5.3.0) page (Ctrl+F for Mcrypt), we should regenerate our application key and re-encrypt all previously encrypted items.

**Comment by logic-dev** [comment]
What encrypted data are we storing that needs re-encrypting?

**Comment by Feld0** [comment]
@logic-dev It looks like you addressed this here: 926e41072139c07768fc6a5a88b142cf493a79a1

How much of this task is addressed by that? I'm not aware of Pony.fm having any us-designed functionality to encrypt anything; Laravel's sessions come to mind but PFM isn't configured to encrypt those.

**Comment by logic-dev** [comment]
From digging through the database and source code, it looks like we only encrypt the cache. Since I'm not willing to spend the processing time to go through and re-encrypt the entire cache, it's better if we just clear it and switch the cipher over

**Comment by logic-dev** [comment]
I'm pretty sure this has been completed. Update has been deployed in prod
