### ISSUE TITLE
Implement oEmbed

### ISSUE THREAD

**Issue by Lavoaster** [Poniverse/Pony.fm#111]
See: http://oembed.com/

This specifically comes from a requirement to implement Pony.fm embeddable's on IPS 4. IPS 4 supports oEmbed out of the box with a plugin required just to add the url to the list of recognised services.

**Comment by logic-dev** [comment]
Sorted. https://pony.fm/oembed?url=https://pony.fm/tracks/1207-equestria-girls-helping-twilight-win-the-crown-wisp-remix
