### ISSUE TITLE
Empty track slugs cause URL problems

### ISSUE THREAD

**Issue by jack126guy** [Poniverse/Pony.fm#119]
If a track's slug turns out to be empty, its URL will be `https://pony.fm/tracks/#####-`, which is not recognized by the track route.

I [raised this issue on MLP Forums](https://mlpforums.com/topic/162600-track-url-not-working/) a few months ago. While I appreciate the (presumed) manual intervention, I think it should be fixed properly.

There are two solutions I can think of:

First, the easy solution: Use a default slug if the slug that Laravel generates is empty. (It could be just a single "-"; hopefully that doesn't cause other problems.)

Second, the harder but perhaps more aesthetically pleasing solution: Allow URLs of the form `https://pony.fm/tracks/#####` (note the lack of hyphen) and use that as the "canonical" URL for tracks with empty slugs.

**Comment by jack126guy** [comment]
Examining the routes, I think the harder solution is probably going to be more trouble than it's worth, so I'd just go for the easy solution. I have a fix on my fork in the `easy-slug-fix` branch.

**Comment by logic-dev** [comment]
Looks good. Can you submit a PR so we can merge this?
