### ISSUE TITLE
Responsify the layout for all things mobile!

### ISSUE THREAD

**Issue by Feld0** [Poniverse/Pony.fm#12]
A fully responsive layout will go a very long way toward making Pony.fm mobile-friendly. Audio playback on modern phones already works and Bootstrap is in place, so this is the next big step to take with the front end.

#21, upgrading to Bootstrap 3, should be done first.

**Comment by Feld0** [comment]
This should be done after #21.

**Comment by Lavoaster** [comment]
Whilst I remember this, I'd almost argue it should be done at the same time. Considering BS3 is mobile first :P

**Comment by logic-dev** [comment]
Would like to redesign the site for mobile instead of my current solution of "Shrink all the things"

**Comment by logic-dev** [comment]
Working on this issue in the material branch

**Comment by Feld0** [comment]
I'm closing this since it's being done as part of #99.
