### ISSUE TITLE
Review genres created during the MLPMA import

### ISSUE THREAD

**Issue by kz** [Poniverse/Pony.fm#19]
Currently, there are too many genres, some of which are inappropriate, duplicate or too vague. It would be appropriate to create a script which merges genres where appropriate. If this gets the go-ahead, discussion will be needed to create a new list of genres.

**Comment by Feld0** [comment]
Genres are best managed by a human being. Aurelleah, Pony.fm's community lead, has volunteered to comb over them and #20 will give him the tools to do it.
