### ISSUE TITLE
Admin interface for Pony.fm's content

### ISSUE THREAD

**Issue by Feld0** [Poniverse/Pony.fm#2]
We need an admin interface for uploading and managing Pony.fm's content, including adding music to existing accounts. At minimum, the following must be possible:

- [x] adding to or editing the list of official show songs
- [x] #20: adding to or editing the list of genres, including the ability to merge two genres (and redirect existing URL's)
- [x] creating an "archived" profile
- [x] editing any Pony.fm profile
- [x] uploading a track and attaching it to any Pony.fm account
- [x] editing and publishing any Pony.fm track
- [x] creating and editing an album on any Pony.fm account

For the purposes of this ticket, all uploading, publishing, and editing abilities normally available to a user must be available to an admin as well; imagine building a toolkit for someone to be an artist's "account manager".

**Comment by logic-dev** [comment]
I'd like to suggest adding a 'report' button (with a subsequent admin interface) to tracks so users can report tracks that feature undeclared explicit content or stolen audio

**Comment by logic-dev** [comment]
This issue is being worked on in branch feature/admin-interface

**Comment by logic-dev** [comment]
Need to fix editing profiles. Manage account -> Tracks shows MY tracks not theirs

**Comment by logic-dev** [comment]
Are the lyrics in the show_songs table being used anywhere?

**Comment by Feld0** [comment]
@logic-dev Not at this time. I originally put that in with the idea of showing the official lyrics of a song on its remixes or even on "resource" pages dedicated to the official song itself, but neither of these features materialized.

**Comment by logic-dev** [comment]
@Feld0 In it's current state, the show song editor does not support lyric editing. Right now it'll fill the lyrics field with a blank string. If this feature is needed in future I will put it in.

**Comment by Feld0** [comment]
@logic-dev Sounds good. 👍

**Comment by Feld0** [comment]
This is now done with the exception of some account-specific functionality (areas under the "Manage Account" tab on profiles) still being tied to the currently logged-in user instead of the user whose profile is currently active.

**Comment by Feld0** [comment]
This is done! 😄  🎉 

![Pinkie Pie partying](https://25.media.tumblr.com/tumblr_lpbpmbXPrc1r0z1wao1_250.gif)
