### ISSUE TITLE
Upgrade to Bootstrap 3

### ISSUE THREAD

**Issue by Feld0** [Poniverse/Pony.fm#21]
Pony.fm is currently on Bootstrap 2. Bootstrap 3 offers a number of improvements, including a proper nested grid and an upstream UI-Bootstrap implementation of [this](https://github.com/Poniverse/Pony.fm/commit/b441a5881914cf428da04f47a1653db11dc1db6c#diff-ac6a52e39e4273e856d1537f1dae33caR1273).

**Comment by Lavoaster** [comment]
I'd highly recommend migrating from ui-bootstrap to [angular-strap](http://mgcrea.github.io/angular-strap/) during this upgrade.

**Comment by logic-dev** [comment]
Site is running fine on Bootstrap 3 in the bootstrap3 branch. The only issue is modals not working which will require installing angular-strap and converting the old code to code that works with angular-strap
