### ISSUE TITLE
Failed uploading tracks, failing to load profile page.

### ISSUE THREAD

**Issue by BCafGun** [Poniverse/Pony.fm#226]
Any uploading .flac currently returns message: "Error: You must upload an audio file!"
Don't know what's with the others yet.
My account page simply unavailable and wont loading.
Upload page also have the strange glitches in the head of page, definitely related with personal data that failing to load.

**Comment by BCafGun** [comment]
Issue still persists. Any chances that it will be fixed? 
Just in case: my profile is Night Blaze. For me it can't be loaded in any way.

**Comment by alexram1313** [comment]
Mitigated as part of the investigation on #239

User profiles are now being unblocked.

**Comment by BCafGun** [comment]
Thank you!
