### ISSUE TITLE
Render URL's in text fields as clickable links

### ISSUE THREAD

**Issue by Feld0** [Poniverse/Pony.fm#24]
All user-entered text in various text boxes around the site is currently displayed verbatim. URL's entered into these areas should be recognized and displayed as clickable, nofollow'd links.

The text areas in question:
- comments
- track descriptions
- album descriptions
- playlist descriptions
- user bios

**Comment by kz** [comment]
Would it be worth adding a "You are now leaving Pony.fm" page as well.

**Comment by Feld0** [comment]
@kz I don't see a need for one at this time.
