### ISSUE TITLE
Timestamps are too precise

### ISSUE THREAD

**Issue by Feld0** [Poniverse/Pony.fm#26]
Timestamps rendered throughout Pony.fm are a little _too_ precise...

![screenshot 2015-11-12 02 14 40](https://cloud.githubusercontent.com/assets/1666960/11115848/34d5e0e4-88e3-11e5-804b-cb78d7efe487.png)

We don't store any timestamps to the microsecond so we shouldn't display or return them that way, either.

**Comment by Lavoaster** [comment]
All returned timestamps should be in ISO 8601 format, which will allow for the removal of the pfmdate filter so we can return to the normal angular one.

E.G Replacing [this](https://github.com/Poniverse/Pony.fm/blob/master/app/Track.php#L311) line with:
```php
$track->published_at->format('c')
```
There may be other dates I'm either not aware of or forgotten about.

**Comment by Feld0** [comment]
Shouldn't Laravel return dates without the milliseconds (when loading models from the database) in the first place? Formatting the date every time we need it doesn't sound like a DRY solution.

**Comment by Lavoaster** [comment]
We're talking about what Carbon does when serialising to a string. The places we're updating these at are presenter methods, so this is about as dry as we can get without some major refactoring.

**Comment by Feld0** [comment]
Huh. So it's Carbon's usual behaviour, then. Well - let's roll with it and format the date when presenting it, then.
