### ISSUE TITLE
Helpers::timestamp format weirdness?

### ISSUE THREAD

**Issue by jack126guy** [Poniverse/Pony.fm#30]
In the `Helpers::timestamp` function (`/app/Library/Helpers.php`) (which is used to format the date in the iframe for track embeds), I think there's some weirdness with the format string on line 74:

    $content = date('F d, o \@ g:i:s a', strtotime($timestamp));

* The `d` specifier adds a leading zero to the day. Is this intended? If not, I think it should be changed to `j`.
* The `o` specifier is the [ISO week-date year](https://en.wikipedia.org/wiki/ISO_week_date), which can deviate from the usual year on dates at the beginning or the end of a year. I don't think this is intended, and this should be changed to `Y`.

**Comment by Feld0** [comment]
Good catches, @jack126guy, and thanks for filing an issue!

I'm not aware of any particular reason for the leading zero nor the ISO week-date year, so updating them is sensible to me. I'll go ahead and do that!
