### ISSUE TITLE
Sub-Navigation bar in Discover area is unintuitive in certain situations

### ISSUE THREAD

**Issue by Lavoaster** [Poniverse/Pony.fm#31]
I was browsing PFM today and clicked on an artist, I then wanted to see their tracks and without thinking just clicked tracks in the subnav, however, that loaded up the normal tracks page. You need to click content on an artists page to view their tracks.

This is quite unintuitive, in my opinion.

The only solution I can think of is moving the current discover nav bar into the main navigation on the left.  Are there any other ways?

## Action items:

- [x] move `Account` from the sidebar to the user dropdown menu
- [x] move `Favourites` from the sidebar to the user dropdown menu
- [x] remove the `Dashboard` link from the sidebar (it's redundant because the logo above it leads to the same place)
- [x] move `Tracks` from the `Discover` subnav into the sidebar
- [x] move `Albums` from the `Discover` subnav into the sidebar
- [x] move `Playlists` from the `Discover` subnav into the sidebar
- [x] move `Artists` from the `Discover` subnav into the sidebar
- [x] rename the current `Playlists` section in the sidebar to `My Playlists` (to differentiate it from the public directory of playlists)

**Comment by Feld0** [comment]
The sidebar already has quite a few links in it and I'm wary of adding too many more. However - "promoting" the `Discover > Artists` tab into the sidebar may alleviate the issue (without moving anything else).

What do you think of this approach, @Lavoaster ?

**Comment by Lavoaster** [comment]
@Feld0 The side navigation has relatively few links, TBH. There's some in there that could be moved into the logged in user dropdown on the top right.

I should have been more clearer in my original post, my intention was not to move all the links to top level items, but sub-items of their parent link, Discover.

**Comment by Feld0** [comment]
I updated the OP with a checklist of exactly what to do, for maximum clarity.

**Comment by Feld0** [comment]
This is now done. Thanks, @CoolApps45 !
