### ISSUE TITLE
Profile button is not highlighted when active

### ISSUE THREAD

**Issue by CoolApps45** [Poniverse/Pony.fm#53]
When logged in, open the dropdown menu (the top right corner) and press 'my profile'. This will open up your profile but there's a couple of issues. The 'artists' button in the sidebar would be selected and in the dropdown the 'my profile' button wouldn't.
When you press 'artists' in the sidebar it should be showing a directory of artists, which is what should be happening.

**Comment by Feld0** [comment]
I'd say the `Artists` button being highlighted is working as intended as it refers to a section of the site - all profiles are part of that section, so the tab highlights when viewing a profile. It's not technically correct when you're viewing the profile of a user with zero published tracks (a non-artist) so an enhancement could be to avoid highlighting it in that case.

`Your Profile` in the dropdown not being highlighted, on the other hand, is definitely a bug.
