### ISSUE TITLE
Show uncropped cover art on track, album, and playlist pages

### ISSUE THREAD

**Issue by Feld0** [Poniverse/Pony.fm#66]
Requested by AnimatronicPony.

The most complex piece of this is generating uncropped images in a smaller size, appropriate for display on these pages.

**Comment by ILikePizza555** [comment]
Just going to add these additional points from our conversation here, so I can keep track:

The new behaviour should be as follows:
- original image remains untouched, like it currently does
- largest resized image should have a fixed width but no fixed height (this is the one that's shown on track/album/playlist pages as the cover)
- the two smaller sizes should remain cropped squares as they are now
- there should be no empty space being added in any sizes
