### ISSUE TITLE
UI tweaks for lossy albums and playlists

### ISSUE THREAD

**Issue by Feld0** [Poniverse/Pony.fm#7]
There are two cases here:

- [x] **Albums and playlists that consist entirely of lossy content** (aka imported from the MLPMA) still show download links for FLAC and ALAC versions. Attempting to download these results in a zip file that doesn't contain any audio files. For these, the lossless download options should not be shown and the download URL's should 404.

- [x] For **albums and playlists with a mix of lossy and lossless content**, the lossless download options should be available but include lossy content in its "master" format. Some form of notice should be displayed to the user when they download one of these to let them know why their lossless download has lossy files in it. In addition to this, the difference in file size must be taken into account.

**Comment by kz** [comment]
Got the first checkbox implemented.

**Comment by kz** [comment]
@Feld0 Should I only use MP3 for the second checkbox in the case that a track is lossy? Also, what would you recommend be the best way to display the notice to the user? A modal after the track starts downloading?

**Comment by Feld0** [comment]
@kz Lossy tracks should be included in a "lossless" album download in whatever their master format is (it's MP3 for a lot of tracks but not all).

A modal after the album download begins seems like a good way to notify the user about this.

**Comment by kz** [comment]
The second checkbox has been implemented: http://i.imgur.com/SMxSNCn.png

**Comment by Feld0** [comment]
🎉  Thanks, @kz !
