### ISSUE TITLE
Switch to PostgreSQL

### ISSUE THREAD

**Issue by Feld0** [Poniverse/Pony.fm#86]
Our choice of MySQL is little more than a vestige from our cPanel days. PostgreSQL is a better SQL database and Pony.fm should use it. Among other great features, it handles migrations better and has a native UUID column type. This should be done before #23.

Things to do:

- [x] deploy a production-grade PostgreSQL server (including automated backups)
- [x] ensure PostgreSQL is provisioned and configured automatically in the dev environment
    - it already comes with the Homestead Vagrant box but we currently ignore its presence
- [x] find, test, and adapt (as necessary) all uses of raw SQL in Pony.fm's codebase to work with PostgreSQL
- [x] write a MySQL -> PostgreSQL migration script; run it automatically in the dev environment if feasible

**Comment by logic-dev** [comment]
This script looks promising for migrating our existing data over https://github.com/lanyrd/mysql-postgresql-converter

**Comment by logic-dev** [comment]
Being worked on in the 'postgres' branch

**Comment by logic-dev** [comment]
Ready to deploy. Maintenance time allocated. Will close once prod is up to date with master

**Comment by logic-dev** [comment]
Almost ready to be closed. Just need to fix album favouriting
