### ISSUE TITLE
MLPMA classification queue

### ISSUE THREAD

**Issue by Feld0** [Poniverse/Pony.fm#91]
#103 should be done first or in parallel with this task.

Among the tracks imported from the MLP Music Archive, nearly 15,000 are currently "unclassified" in Pony.fm's taxonomies. An admin UI should be built for these that allows a Pony.fm admin to easily go through and tag them correctly as remixes, original songs, etc. and fill in any missing metadata.

Unclassified tracks have a `track_type_id` of 6 in the `tracks` table.

**Comment by logic-dev** [comment]
v1 of this is currently rolling out now

**Comment by logic-dev** [comment]
It's live! Good luck to the folks who have to tag 17k songs by hand
