### ISSUE TITLE
Material redesign

### ISSUE THREAD

**Issue by logic-dev** [Poniverse/Pony.fm#99]
The current UI is designed for desktop use. Large modifications to the design have been made to support a mobile version. Going forward, we need a more responsive layout. Google's Material Design spec will provide a good reference for how we layout the site and how we use animations. https://material.google.com

The 'material' update will be handled in the material branch. The update will be launched in 2 waves. First, a redesign of the app shell, user profiles, track, album and playlist detail pages. This will be released very soon.
- [x] Navbar and sidebar
- [x] User profiles
- [x] Track page
- [x] Album page
- [x] Playlist page
- [x] Track editor

The second wave will be completed after the Ponify import. Contents of this patch are still being evaluated.
- [ ] New admin page with dark theme (fancy!)
- [ ] Uploader moved to a [FAB](https://material.google.com/components/buttons-floating-action-button.html) in corner

**Comment by Feld0** [comment]
@logic-dev: Does this task supersede/replace #12?

**Comment by logic-dev** [comment]
Since this is more than a mobile layout, yes

**Comment by berwyn** [comment]
Are we planning to use [Angular Material](https://material.angularjs.org/latest/) or something like [Material Design Lite](https://getmdl.io/)?

**Comment by logic-dev** [comment]
I'm currently using custom code. I might use a JS library for the ripple effect

**Comment by Lavoaster** [comment]
@logic-dev Any reason to opt for custom as apposed to the ones suggested?

**Comment by logic-dev** [comment]
Not really. I've just been pulling code that I used to build my personal site. Don't like the idea of adding an entire library when I can recreate the effect with a few lines of code

**Comment by berwyn** [comment]
It seems better to use a library like the aforementioned because we get
Flexbox polyfills as well. Pretty sure they're also modular, so we can pull
in the bits we need as we need them.

**Comment by logic-dev** [comment]
Fair enough I'll Angular Material a look

**Comment by logic-dev** [comment]
Core design is finished. Just need to fix some bugs and we'll be good

**Comment by logic-dev** [comment]
I'm ditching this redesign in favour of a complete rewrite just to get off CoffeeScript and upgrade to something like React
